# Generated by Django 5.1.5 on 2025-02-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tag_rename_name_course_title_and_more'),
        ('users', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses_enrolled',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course'),
        ),
    ]
